export default {
	$window: $(window),
	$document: $(document),
	$html: $(document.documentElement),
	$body: $(document.body),
	$page: $('.page'),
	$pageContent: $('.page__content'),
	$pageBlock: $('.page__block'),
	$header: $('.header'),
	$progress: $('.progress-bar'),
	$share: $('.share'),
	$nav: $('.nav'),
	$navItem: $('.nav__item'),
	$navPage: $('.nav-page'),
	$navItemToMain: $('.nav__item--to-main'),
	$navItemScroll: $('.nav__item--scroll'),
	$navProgress: $('.nav__progress'),
	$navText: $('.nav__text'),
	$navClose: $('.mobile-nav__close'),
	$navMobile: $('.mobile-nav__item'),
	$blockInfo: $('.info'),
	$info: $('.info__fixed'),
	$infoBlock: $('.share__info'),
	$blockHero: $('.hero'),
	$blockHero1: $('.hero[data-item="1"]'),
	$blockHeroLeft: $('.hero__left-block'),
	$hero1Bg: $('#hero1 .hero__bg img'),
	$bgText: $('.info__bg-text'),
	$heroImg: $('.hero__img'),
	$heroInfo: $('.hero__info'),
	$heroQuote: $('.hero__quote'),
	$heroQuoteItem: $('.hero__quote-item'),
	$heroNameTitle: $('.hero__name-title'),
	$banner: $('.banner'),
	$otherHeroes: $('.other-heroes'),
	$burger: $('.js-burger'),
	$dataScrollSpeed: $('[data-scroll-speed]'),
};
